name: 📊 Update Organization Profile

on:
  workflow_run:
    workflows: ["🎯 E2E Tests & Report"]
    types: [completed]
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 업데이트
  workflow_dispatch:

jobs:
  update-profile:
    name: 📈 Update Org Profile Stats
    runs-on: ubuntu-latest
    if: github.repository == 'sesac7-hello-pet-v2/hello-pet-v2'

    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ORG_PROFILE_TOKEN }}  # 필요 시 설정
        repository: 'sesac7-hello-pet-v2/.github'

    - name: 📊 Update README with test results
      run: |
        # 테스트 결과 API에서 가져오기
        TEST_STATUS=$(curl -s "https://api.github.com/repos/sesac7-hello-pet-v2/hello-pet-v2/actions/workflows/e2e-test.yml/runs?per_page=1" | jq -r '.workflow_runs[0].conclusion')
        RUN_DATE=$(curl -s "https://api.github.com/repos/sesac7-hello-pet-v2/hello-pet-v2/actions/workflows/e2e-test.yml/runs?per_page=1" | jq -r '.workflow_runs[0].updated_at')

        # README.md 업데이트 (마커를 사용하여 특정 섹션만 업데이트)
        sed -i '/<!-- E2E_STATS_START -->/,/<!-- E2E_STATS_END -->/c\
        <!-- E2E_STATS_START -->\
        ## 🧪 E2E 테스트 현황\
        \
        [![E2E Tests](https://github.com/sesac7-hello-pet-v2/hello-pet-v2/actions/workflows/e2e-test.yml/badge.svg)](https://github.com/sesac7-hello-pet-v2/hello-pet-v2/actions/workflows/e2e-test.yml)\
        \
        **📊 [실시간 테스트 리포트](https://sesac7-hello-pet-v2.github.io/hello-pet-v2/)**\
        \
        - **마지막 실행**: '"$RUN_DATE"'\
        - **상태**: '"$TEST_STATUS"'\
        - **테스트 환경**: Playwright + Chromium\
        <!-- E2E_STATS_END -->' README.md

    - name: 💾 Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "📊 Update E2E test stats"
        git push